server:
  port: 8082
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
  instance:
    hostname: localhost
spring:
  application:
    name: customer-service
  datasource:
    password: root
    url: jdbc:mysql://localhost:3306/e-mandi?useSSL=true
    username: root
  jpa:
    hibernate:
      ddl-auto: 'update '
    show-sql: true