server:
  port: 8084
#eureka:
#  client:
#    register-with-eureka: true
#    fetch-registry: true
#  instance:
#    hostname: localhost

#cloud:
#  aws:
#    region:
#      static: us-east-1
#      auto: false
#    credentials:
#        access-key: 
#        secret-key: 

spring:
  profiles:
    active: local
